# -*- coding: utf-8 -*-

BROADCAST_PLAY = 1
BROADCAST_STOP = 2
SET_VIDEO_WINDOW = 3
UNSET_VIDEO_WINDOW = 4
PLAY_STREAM = 5
EXIT = 6
STOP_STREAM = 7
PAUSE_STREAM = 8
SEEK_STREAM = 9
CREATE_APPLICATION = 10
PAGE_LOAD_FINISHED = 11
BROADCAST_HIDDEN = 12
RESTORE_BROADCAST = 13
SET_STREAM_STATE = 14
SET_CHANNEL = 15
PREV_CHANNEL = 16
NEXT_CHANNEL = 17
LOG = 18

OPEN_URL = 101
SET_CURRENT_CHANNEL = 102
QUIT = 103
